### ISSUE TITLE
Cannot find libpapi.so

### ISSUE THREAD

**Issue by karanaggarwal1994** [quepas/mPAPI#6] opened 2019-12-05 17:05 UTC
>> ev = mPAPI_register({'FP_ARITH:SCALAR_SINGLE', 'L1D:REPLACEMENT', 'PAPI_L2_ICA'})

I getting the following error when I run the above command. I have install papi in /usr/local/ directory.

Invalid MEX-file '/home/user/mPAPI/mPAPI_register.mexa64':
libpapi.so.5.7: cannot open shared object file: No such file or
directory

**Comment by quepas** [comment] 2019-12-08 12:39
@karanaggarwal1994 Could you verify that PAPI is installed correctly by running following commands in a terminal and copying their output:

1. `papi_version`
2. `whereis libpapi`
3. `ldconfig -p | grep libpapi`
4. `locate libpapi`

Thank you.

**Comment by karanaggarwal1994** [comment] 2019-12-08 13:44
Hi @quepas,
Here is the output of the commands you requested.

1. `papi_version`
PAPI Version: 5.7.1.0
2.` whereis libpapi`
/usr/local/lib/libpapi.so /usr/local/lib/libpapi.a /home/karan/papi_install/lib/libpapi.so /home/karan/papi_install/lib/libpapi.a
3. `ldconfig -p | grep libpapi`
libpapi.so.5 (libc6,x86-64) => /lib64/libpapi.so.5
4.`locate libpapi`
locate: can not stat () `/var/lib/mlocate/mlocate.db': No such file or directory

**Comment by quepas** [comment] 2019-12-08 13:57
Hi @karanaggarwal1994 ,
Thank you. It seems everything is OK, except for the dynamic link to the shared library (3rd command `ldconfig`). What OS are you using?

## Command line

If you build the MEX files from the command line change `-L/usr/local/lib/` to `-L/lib64/`.

```sh
mex -I/usr/local/include mPAPI_register.c -L/lib64/ -lpapi -output mPAPI_register
```
## Build script

If you use the `build_all.sh` script, then in the file [`build_matlab.sh`](https://github.com/quepas/mPAPI/blob/master/build_matlab.sh), change each occurrence of `-L/usr/local/lib/` to `-L/lib64/` so that lines:

```sh
$MEX CXX=$COMPILER CC=$COMPILER GCC=$COMPILER CXXFLAGS='$CXXFLAGS -std=c++0x' -I/usr/local/include mPAPI_groupEvents.cpp -L/usr/local/lib/ -lpapi -output mPAPI_groupEvents -outdir $OUT_DIR
...
```
become
```sh
$MEX CXX=$COMPILER CC=$COMPILER GCC=$COMPILER CXXFLAGS='$CXXFLAGS -std=c++0x' -I/usr/local/include mPAPI_groupEvents.cpp -L/lib64/ -lpapi -output mPAPI_groupEvents -outdir $OUT_DIR
...
```
It is a long shot, but who knows :) If it won't work we will figure out something else. Good luck.

**Comment by karanaggarwal1994** [comment] 2019-12-09 03:48
Hi @quepas,
It didn't help. I am using CentOS 8 and Matlab 2019b.

**Comment by karanaggarwal1994** [comment] 2019-12-09 03:56
I figured out what was the issue. When I checked /lib64/, it had 3 libraries:
libpapi.so.5
libpapi.so.5.6.0
libpapi.so.5.6.0.0

However, when I ran the command on Matlab, it was searching for  
libpapi.so.5.7

Then I created soft link to create libpapi.so.5.7 and the error was removed. But then I got following error:
```
Error using mPAPI_register
Failed to create an event set.. Reason: PAPI hasn't been initialized yet
```

**Comment by quepas** [comment] 2019-12-09 13:37
Nicely done @karanaggarwal1994! An interesting development. 

This error originates in [line 56 of `mPAPI_register` function](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L56). Surprisingly, before the call to `PAPI_create_eventset` function, there are several other functions from the PAPI library which, I think, require initialised library (more precisely: [`PAPI_get_opt`](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L24), and [`PAPI_event_name_to_code`](https://github.com/quepas/mPAPI/blob/master/mPAPI_utils.hpp#L87) in `mPAPI_utils.m`).

So I have three theories:
1) The call to [`PAPI_library_init`](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L16) fails → problem with PAPI/MATLAB/OS. I will install MATLAB R2019b to see if I could reproduce it. I am using the same version of PAPI (however, I don't have previous versions and only `5.7.1.0`).
2) Only [`PAPI_create_eventset`](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L54) fails, but with an inadequate error message → please try to call the `mPAPI_register` with just a one "safe" and "sure" performance event which is `PAPI_TOT_CYC` (or `PAPI_TOT_INS`). Maybe the problem is that you try to use non-existent or troubled performance event.
3) Honestly, I forgot while writing about the previous two. But it was something about the mix-up with PAPI libraries, and wrong functions were linked.

Talk to you soon.

**Comment by quepas** [comment] 2019-12-09 20:36
@karanaggarwal1994 For know, before we solve the problem, check out the official API for MATLAB from PAPI https://bitbucket.org/icl/papi/src/master/src/Matlab/. Especially, if what you need are only performance events in the counting mode. What are you working on?

I have validated in the source code of the PAPI, that both functions,  [`PAPI_get_opt`](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L24), and [`PAPI_event_name_to_code`](https://github.com/quepas/mPAPI/blob/master/mPAPI_utils.hpp#L87), perform checks if PAPI is initialized. Similar to this code:

```C
if ( init_level == PAPI_NOT_INITED )
    papi_return( PAPI_ENOINIT );
```
However, the [`PAPI_create_eventset`](https://github.com/quepas/mPAPI/blob/master/mPAPI_register.cpp#L54) also has this check and it fails, but not the previous ones. Astounding. 

With the last [commit](https://github.com/quepas/mPAPI/commit/971ad2974a2b40342e7fe515b7f68e180bdddcc0) I have added checks to determinate if the PAPI library was initialized successfully.

**Comment by karanaggarwal1994** [comment] 2019-12-10 06:10
@quepas I am working on optimizing a computational neuroscience problem. The algorithm is written in MATLAB while the compute-intensive part is written in CUDA. I want to analyze my optimizations by measuring the data transfer between CPU-GPU, total FP ops, cache hits/misses, GFLOPS and other such info.

**Comment by karanaggarwal1994** [comment] 2019-12-24 06:27
Hi @quepas 
I have run following command in MATLAB.
```
ev = mPAPI_register({'perf::CPU-CLOCK','perf::INSTRUCTIONS'}, 'true')
mPAPI_tic(ev)
mPAPI_toc(ev)
ans =

  1×2 int64 row vector

   12497052    9662402
```
I haven't run any code in between
```
mPAPI_tic(ev)
mPAPI_toc(ev)
```

Then, what do the results mean? Can you help how to use mPAPI?

**Comment by quepas** [comment] 2019-12-24 06:58
Hi @karanaggarwal1994 ! Sorry, I wasn't replying because I was defending my PhD :man_student: 

The work you have described is really interesting. I will help you as much as I can.

OK, so the two values you have obtained, `[12497052, 9662402]` are the values of `perf::CPU-CLOCK` and `perf::INSTRUCTIONS`. Although you haven't run any code in between, MATLAB always performs some instructions there (the interpretation, preparing the code for Just-In-Time compilation, the overhead of running our mPAPI tool -- _observer effect_). What MATLAB is not performing in such case are floating-point operations. So if you use a performance event like `PAPI_DP_OPS` or `PAPI_VEC_DP` (if available on your machine, you can validate this by running command `papi_avail -a`), then you will obtain `0`.

The last argument you have used `'true'` (should be actually just `true`) tells if you measure performance events in a multiplexing mode. The multiplexing mode is a way to cheat and measure more performance events that you have hardware performance counters on your CPU (which store performance events). This mode works by measuring performance event for a short time during the program execution, and then, extrapolating the results. You can read about it from the [PAPI wiki](https://icl.cs.utk.edu/projects/papi/wiki/Multiplexing). In general, you can skip this parameter if you have a small number of performance events, thus, turning off the multiplexing. Moreover, multiplexing is not recommended for programs with time-varying behaviour, because the extrapolation will be erroneous it that case.

I am glad you have managed to run mPAPI on your machine. What have you done to do so? :)

**Comment by karanaggarwal1994** [comment] 2019-12-24 07:57
Congratulations @quepas. Hopefully, with your help, I'll defend my Masters' thesis soon. 

I ran the performance event `PAPI_DP_OPS` and `PAPI_VEC_DP` but still, the output is not `0`.

I installed stable PAPI version 5.7.0 instead of PAPI 5.7.1. PAPI developers have updated their high-level APIs in PAPI 5.7.1 because of which the issue was there. 

Also, I used PAPI https://bitbucket.org/icl/papi/src/master/src/Matlab/ as you suggested. However, I am getting the error `"Error getting flops."`.

**Comment by quepas** [comment] 2019-12-24 09:08
@karanaggarwal1994 thank you! :) I am sure you will too!

So, such behaviour of non-zero FP-operations for an empty code I have noticed on some CPUs. What kind of a CPU do you have? Especially I am interested in the micro-architecture: Skylake, Haswell etc. The problem here might be that for the given CPU, performance events can be inaccurate (common case is their overcount).

Interesting! I need to update mPAPI soon then :) Thank you.

The error you get (`"Error getting flops."`) is a common one. In their code and API for MATLAB, they are assuming that very particular performance events exist on your CPU. Apparently, they are not, hence, the error. If you use these two functions with the available `event` on your CPU, then you should be fine:

```
%    PAPI('start', 'event', ...) - 
%                                 Begin counting the specified events.
%    [val, ...] = PAPI('stop')  - Stop counting and return the current values.
```

These calls do basically the same as `mPAPI_register`, `mPAPI_tic`, `mPAPI_toc` do combined.

**Comment by karanaggarwal1994** [comment] 2019-12-24 09:39
I am using Intel Skylake machine.

```

%    PAPI('start', 'event', ...) - 
%                                 Begin counting the specified events.
%    [val, ...] = PAPI('stop')  - Stop counting and return the current values.
```
I ran this code. It is working :). But, again the problem with the above code is that it not giving output as `0`.

**Comment by quepas** [comment] 2019-12-25 12:14
@karanaggarwal1994 it is a mystery again! I have checked the code of [MATLAB interface in PAPI](https://bitbucket.org/icl/papi/src/master/src/Matlab/PAPI_Matlab.c) and it seems it doesn't perform any floating-point operations (except for some time computation in `flip`/`flop` functions). It will still generate some processor cycles and processor instructions as it requires to run the code conducting the measurements. If the values you get are quite repetitive, you could treat them as bias and just subtract them from the measurements obtained during your program execution. Good luck! :)

**Comment by quepas** [comment] 2020-02-15 22:09
@karanaggarwal1994 Congratulation on the ICS paper! :) I am going to close this issue because I am moving the development of mPAPI to https://github.com/quepas/pep-talk (which will include interfaces for other languages: Python etc.). In case of further problems/requests/questions, feel free to ask anytime.

**Closed as completed by quepas** 2020-02-15 22:09 UTC
Labels: help wanted
